# Generated by Django 4.2.20 on 2025-04-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="lastname",
            new_name="last_name",
        ),
    ]
