# Generated by Django 4.2.20 on 2025-04-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_remove_department_created_by_and_more"),
        ("account", "0003_customuser_created_at_customuser_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="organization.department",
            ),
        ),
    ]
