default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: black
        name: Black Formatter
        entry: black
        language: python
        types: [python]
        additional_dependencies: [black]

      - id: isort
        name: Isort Import Sorter
        entry: isort
        language: python
        types: [python]
        additional_dependencies: [isort]
        args: ["--profile=black"]

      - id: flake8
        name: Flake8 Linter
        entry: flake8
        language: python
        types: [python]
        additional_dependencies: [flake8]
        args: ["--max-line-length=88", "--ignore=E501"]  # ✅ Ignores long-line errors
        exclude: "(migrations|.venv|__pycache__)"  # ✅ Ignores unnecessary files

      - id: bandit
        name: Bandit Security Checker
        entry: bandit
        language: python
        types: [python]
        additional_dependencies: [bandit]
