# Generated by Django 4.2.20 on 2025-04-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
