# Generated by Django 4.2.20 on 2025-04-10 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import task_management.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "get_latest_by": "start_date",
                "ordering": ["start_date", "priority"],
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[task_management.models.validate_due_date],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[task_management.models.validate_start_date],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("I", "In Progress"),
                    ("C", "Completed"),
                    ("O", "Overdue"),
                    ("H", "On Hold"),
                    ("X", "Cancelled"),
                ],
                default="P",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="taskcollaborator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
