# Generated by Django 4.2.20 on 2025-04-14 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0004_projectcollaborator_is_deleted"),
        ("task_management", "0002_alter_task_options_alter_task_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="project_management.project",
            ),
            preserve_default=False,
        ),
    ]
