# Generated by Django 4.2.20 on 2025-04-08 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectAssigned",
            new_name="ProjectCollaborator",
        ),
        migrations.RemoveField(
            model_name="project",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborated_projects",
                through="project_management.ProjectCollaborator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
