# Generated by Django 4.2.20 on 2025-04-09 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project_management",
            "0002_rename_projectassigned_projectcollaborator_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectcollaborator",
            old_name="assigned_at",
            new_name="addeed_at",
        ),
        migrations.AddField(
            model_name="projectcollaborator",
            name="added_by",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="added_collaborators",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
