# Generated by Django 4.2.20 on 2025-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_management",
            "0003_rename_assigned_at_projectcollaborator_addeed_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcollaborator",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
